export const FIND_ALL_BOOK = 'FIND_ALL_BOOK'
export const RELEASE_NEW_BOOK = 'RELEASE_NEW_BOOK'
export const FIND_ONE_BOOK = 'FIND_ONE_BOOK'
export const AUTH_REGIST = 'AUTH_REGIST'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'